version: "3"
services:

  mirror:
    image: bearstech/http-mirror
    labels:
      traefik.frontend.rule: Host:mirror.demo.example.com

  mirror.demo.example.com:
    image: traefik:1.7.4
    expose:
      - 80
      - 443
      - 8080
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pki/star-key.pem:/pki/star-key.pem
      - ./pki/star.example.com.crt+chain:/pki/star.example.com.crt+chain
      - ./star.example.com.toml:/etc/traefik/conf.d/star.example.com.toml

  client:
    links:
      - mirror.demo.example.com
    build:
      dockerfile: Dockerfile.client
      context: .
    command: curl -vs https://mirror.demo.example.com
    